### ISSUE TITLE
faltan archivos del proyecto: "index.html"

### ISSUE THREAD

**Issue by Lsickle** [majomaken/housegamingproyect#5]
faltan los archivos del proyecto: index, pagina de inicio y demas archivos html... los mismos no necesitan de la base de datos para ser estructurados ni maquetados... tambien es importante tener en un solo lugar todos los demas archivos como por ejemplo el archivo deonde dice como esta distribuido el trabajo del proyecto

**Comment by majomaken** [comment]
Ya se completo esto ya esta el archivo para su modificación
